name: Update GitHub Stats

on:
  schedule:
    - cron: '0 */12 * * *'  # Cada 12 horas
  workflow_dispatch:         # Para lanzarlo manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate GitHub Stats SVG
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GH_PAT }}
          user: ngpalma
          base: "activity, community, repositories, metadata"
          config_timezone: America/Argentina/Buenos_Aires
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
